name: Deploy to Production

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types: [ closed ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sleep 2
          
      - name: Run tests
        run: |
          echo "Running tests..."
          sleep 3
          echo "✅ All tests passed!"

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Production
        run: |
          echo "🚀 Deploying to production..."
          echo "Environment: Production"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          sleep 5
          echo "✅ Deployment successful!"
          
      - name: Notify Success
        run: |
          echo "📧 Sending deployment notification..."
          echo "Deployment completed at $(date)"

  build-and-deploy:
    name: Build and Deploy Application
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Application
        run: |
          echo "🔨 Building application..."
          echo "Building for production environment"
          sleep 4
          echo "✅ Build completed successfully!"
          
      - name: Deploy to Staging
        run: |
          echo "🚀 Deploying to staging..."
          sleep 3
          echo "✅ Staging deployment successful!"
          
      - name: Deploy to Production
        run: |
          echo "🚀 Deploying to production..."
          echo "Final production deployment"
          sleep 5
          echo "✅ Production deployment successful!"
